name: credpal
description: "An Interactive CredPal Test Application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^5.0.0
  flutter_svg: ^2.2.3
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir Light.ttf
          weight: 300
        - asset: assets/fonts/Avenir Regular.ttf
          weight: 400
        - asset: assets/fonts/Avenir Heavy.ttf
          weight: 900
    - family: Axiforma
      fonts:
        - asset: assets/fonts/Axiforma-Light.ttf
          weight: 300
        - asset: assets/fonts/Axiforma-Regular.ttf
          weight: 400
        - asset: assets/fonts/Axiforma-Bold.ttf
          weight: 700
